----------------------------------------------- en -----------------------------------------------

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.address';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','Address','Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','CellPhoneInvalid','Invalid Phone Number');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','LocalArea','Region');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','PleaseInputAddress','Please Input Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','PleaseInputCellPhone','Please Input Mobile No');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','PleaseInputContact','Please Input Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','PostalCode','Postal Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','ReceiverAddress','Recipient Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','SelectLocalArea','Please Selec Region');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','SetDefault','Set Default');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','Submit','Submit');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','UserName','Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','UserTel','Telephone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','YourName','Your Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','YourTel','Your Tel');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','TelCode','Telephone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','English','English');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','zhCN','Chinese style');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','zhHK','Chinese complex font');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','Country','Country');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.address','AddressLanguage','Select Language');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.addresslist';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.addresslist','AddAddress','Add Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.addresslist','Address','Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.addresslist','DefaultAdd','Default Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.addresslist','Delete','Delete');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.addresslist','DetermineDelete','Are You Sure to Delete Address?');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.addresslist','Modify','Modify');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.addresslist','Name','Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.addresslist','Tel','Tel');


delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.creditcardpay';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.creditcardpay','ScanNumber','ScanNumber');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.creditcardpay','CurrencyNumber','CurrencyNumber');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.creditcardpay','CardNumber','CardNumber');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.creditcardpay','BecomeDate','BecomeDate');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.creditcardpay','AuthorizationCode','AuthorizationCode');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.creditcardpay','Money','Money');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.creditcardpay','Holder','Holder');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.creditcardpay','Voucher','Voucher');



delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.bonus';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','Bonus','Bonus');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','BonusBalance','Bonus Balance');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','BonusCenter','Bonus Center');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','Date','Date');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','Detailed','Detail');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','ExpiredDate','Expiry Date');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','NoMore','No More Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','NoRecordFound','Record Not Found');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','Unit','pts');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.bonus','UserCenter','VIP Grade Center');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.cart';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Amount','Amount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Calculating','Calculating');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','CheckRequire','Please Select Checkout Item');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Color','Color');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Discount','Discount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','NetAmt','Net Amount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Price','Price');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Promotion','Promotion');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','PromotionLess','Promotion Less');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','PromotionServerError','Promotion Server Error');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Quantity','Quantity');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Size','Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','All','All');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Count','Quantity');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Discount','Discount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','PayNow','Pay Now');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','PromotionLess','Promotion Less');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','SelectAll','Select All');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Settle','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','Total','Total');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.cart','WithoutCarriage','Without Shipping');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.commonfooter';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Cart','Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Confirm','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','CreateFailed','CreateFailed');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','DuplicateEmail','DuplicateEmail');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','DuplicateMobile','DuplicateMobile');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Email','Email');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','FirstName','First Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Home','Home');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','HomePage','Homepage');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','InvalidRegId','InvalidRegId');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Keep','Keep');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','LOGIN','LOGIN');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','LastName','Last Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','LineUpInput','LineUpInput');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Login','Login');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','LoginSuccess','Login Successfully');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Logout','Logout');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','NewVip','New Vip');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Phone','Phone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','PleaseInputTelOrEmail','Please Input Telephone No or Email');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','PleaseInputUser','Please Input Tel or Email or VIP Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','RegSuccessAndLogin','Are You Sure to Register New Member');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Scan','Scan');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','ScanResult','Scan Result');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Set','Set');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','TelOrEmailNotValid','Tel or Email Invalid');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','TelOrEmailOrVipcode','Tel or Email or VIP Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Total','Total');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','User','User');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','VIP','VIP');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','Vip','VIP');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','VipCode','VIP Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','VipLogin','VIP Login');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.commonfooter','results','Results');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.coupon';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','AlreadyUsed','Used');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','Cancel','Cancel');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','Confirm','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','EffectDate','Effective Date');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','ExpiryDate','Expiry Date');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','GiftFriend','Gift Friend');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','HasExpired','Expired');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','NoMore','No More Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','NoRecordFound','Record Not Found');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','NotUsed','Available');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','Terms','Terms');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','TicketNumber','Ticket Number');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.coupon','UseDate','Used Date');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.giftcert';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','AlreadyUsed','Used');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','Cancel','Cancel');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','Confirm','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','EffectDate','Effective Date');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','ExpiryDate','Expiry Date');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','GiftFriend','Gift Friend');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','Giftcert','Gift Cert');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','HasExpired','Expired');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','NoMore','No More Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','NoRecordFound','No Record Found');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','NotUsed','Available');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','Terms','Terms');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','TicketNumber','Ticket Number');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.giftcert','UseDate','Used Date');


delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.home';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Bonus','Bonus');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','BrowseHistory','Browsing History');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','CHECK','Check');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Confirm','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Coupon','Coupon');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','GiftCert','Gift Cert');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','History','History');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Hot','Hot');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','ItemCode','Item Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','LikedItem','Liked Item');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Logout','Logout');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','LogoutConfirm','Are You Sure To Logout?');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','LogoutSuccess','Logout Successfully');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','NearestStore','Nearest Store');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','NewArrival','New Arrival');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','PleaseInputItemCode','Please Input Item Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','PleaseInputStoreZone','Please Input Store Zone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','PleaseSelectStoreCode','Please Select Store Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Radar','Radar');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Recommend','Recommendation');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','STORAGE','Storage');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Sales','Sales');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Scan','Scan');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','SelectStore','Select Store');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','SelectStoreZone','Select Store Zone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','SelectZone','Select Zone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Shopping','Shopping');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Stock','Stock');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','StockCheck','Stock Check');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','StoreList','Store List');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','StoreMap','Store Map');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Vip','VIP');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','VipScan','VIP Scan');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Wallet','Wallet');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.home','Zone','Zone');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.itemcat';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','%OFF','%OFF');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','APPLY','APPLY');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','AddToCardSuccess','Added to Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','AddToCart','Add To Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Color','Color');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Count','Quantity');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Filter','Filter');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Hot','Hot');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Keywords','Keywords');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Login','Login');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','New','New');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','NoMoreRecords','No More Result');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Notfound','Cannot find more record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Password','Password');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','PasswordNotCorrect','Password Incorrect');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Price','Price');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','PwdCannotEmpty','Please Input Password');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','SEARCH','SEARCH');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Scan','Scan');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','ScanResult','Scan Result');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','SelectColorSizeFirst','Select Color Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','Size','Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','StaffCode','Staff Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','StaffCodeCannotEmpty','Please Input Staff Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','StaffLogin','Staff Mode');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','StaffMode','Staff Mode');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemcat','VipMode','View Mode');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.itemdetail3d';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','%OFF','%OFF');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','AddToCardSuccess','Added to Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','AlreadySold','Sold');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','Carriage','Shipping');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','Color','Color');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','Count','Quantity');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','Delivery','Delivery');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','Footprint','Footprint');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','MyUser','My User');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','Qty','Qty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','SelectColorSizeFirst','Select Color Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','ShowDetail','Show Detail');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','Size','Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','VFavourite','V Favorite');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetail3d','VHome','V Home');


delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.itemdetailfooter';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','AddToCart','Add To Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','AlreadyLike','Liked');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','BuyNow','Checkout');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','Cart','Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','Comment','Comment');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','Like','Like');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','LikeSuccess','Like Success');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','LoginFirst','Please Login');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','Share','Share');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.itemdetailfooter','UnlikeSuccess','Unlike Success');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.login';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','Keep','Keep');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','Login','Login');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','LoginSuccess','Login Successfully');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','Logout','Logout');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','PleaseInputTelOrEmail','Please Input Telephone No or Email');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','PleaseInputUser','Please Input User');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','RegSuccessAndLogin','Registration Successful');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','Register','Register');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','ScanQrcode','Scan QR Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','ScanResult','Scan Result');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','Set','Set');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','TelOrEmailNotValid','Tel or Email Invalid');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','TelOrEmailOrVipcode','Tel or Email or VIP Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.login','VipLogin','VIP Login');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.orderlist';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','CanCancel','Cancel');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Canceled','Canceled');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Cancelled','Cancelled');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Color','Color');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Items','Items');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','NoMore','No More Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','NoRecordFound','No More Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','OrderNumber','Order Number');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','OrderTime','Order Time');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Price','Price');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Qty','Qty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Size','Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Status','Status');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','Total','Total');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','TotalAmt','Total Amount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','ViewLogistics','View Logistic');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','WaitDelivery','Order Processing');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','WaitPay','Pending');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.orderlist','WaitReceive','Order Dispatched');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.search';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','%OFF','折');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','AddToCardSuccess','Added to Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','AddToCart','Add To Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','Color','Color');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','Count','Quantity');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','KeywordNull','Please Input Keyword');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','NoCode','NoCode');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','NoItemFound','Record Not Found');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','NoMoreRecord','No More Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','PleaseInputKeyword','Please Input Keyword (Style Code / Description / Color / Size)');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','ScanResult','Scan Result');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','SelectColorSizeFirst','Select Color Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','Size','Size');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.setting';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.setting','Auto','Auto');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.setting','ClearCache','Clear Cache');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.setting','CurrentVersion','Current Version');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.setting','SystemLanguage','System Language');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.settle';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Add','Add');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','AddressRequired','Please Input Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Amount','Amount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','AvailQty','Available Qty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','BaseAmount','Base Amount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Bonus','Bonus');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','BonusDesc','Bonus Points');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','BousRedeem','Bonus Redeem');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Cancel','Cancel');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','CardNoDuplicate','CardNoDuplicate');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Change','Change');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Color','Color');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','CompleteOrderConfirm','Are You Sure To Complete The Order?');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Confirm','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Coupon','Coupon');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Currency','Currency');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','DeliveryMethod','Delivery Method');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Discount','Discount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','DocNoEmpty','DocNoEmpty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','DocNotFound','Document No. Not Found');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','ExceedBatchLimit','ExceedBatchLimit');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','ExceedMaxPackages','ExceedMaxPackages');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','ExceedQtyLimit','ExceedQtyLimit');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Express','Express');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','FlowMethod','Please Select');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Issue','Issue');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Item','Item');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','LeaveAMessageHere','Leave A Message Here');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','LineUpInput','Input Line Up No.');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','LineUpNoMustHasValue','Please Input Line Up No.');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','LineUpNum','Line Up No.');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','LineUpQrcode','Line Up QR Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','MaxPackages','MaxPackages');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','MessageBoard','Message Board');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','More','More');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','NoLineUpNoAvailable','NoLineUpNoAvailable');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PLU','PLU');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Paid','Paid');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PaidAmount','Paid Amount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PaidAmountNotEnough','Insufficient Payment Amount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PayAmountCannotBeZero','Pay Amount Cannot Be Zero');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Payment','Payment');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PickUpAddress','Pickup Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PickUpBySelf','Pickup');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PickUpStore','Pickup Location');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PleaseInputCouponNo','Please Input Coupon No');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','PleaseInputLineUpNum','PleaseInputLineUpNum');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Price','Price');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Qty','Qty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','QuotaLimit','QuotaLimit');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Receiver','Recipient');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','ReceiverAddress','Recipient Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Redeem','Redeem');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','RedeemBonus','Redeem Bonus');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Required','Required');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Save','Save');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','ScanQrcode','Scan QR Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','SelectAddress','Select Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','ServerError','Server Error');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','ShippingMethod','Shipping Method');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','ShowQrcode','Show QR Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Size','Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','StoreCodeEmpty','StoreCodeEmpty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','TenderNull','Please Select Payent Tender');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','TillIdEmpty','TillIdEmpty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','Total','Total');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','TotalAmount','Total Amount');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','TotalAvailQty','TotalAvailQty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','UseQty','UseQty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','lineUpNoOnUse','lineUpNoOnUse');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settle','pts','pts');


delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.settlefooter';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settlefooter','Complete','Complete');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settlefooter','Confirm','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.settlefooter','Share','Share');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.staff';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.staff','Logout','Logout');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.staff','LogoutConfirm','Logout Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.staff','MyOrders','My Sales Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.staff','ReceiverAddress','Recipient Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.staff','Set','Settings');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.stafflogin';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','Configuration','Configuration');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','LogoutSuccess','Logout Successfully');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','Notfound','Record Not Found');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','Password','Password');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','PasswordNotCorrect','Password Incorrect');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','PleaseInputPwd','Please Input Password');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','PleaseInputUser','Please Input Staff Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','SignIn','Sign In');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','StaffCode','Staff Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','StaffLogoutConfirm','Staff Logout Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stafflogin','StaffSignIn','Staff Sign In');


delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.stock';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','Cancel','Cancel');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','Confirm','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','Go','Go');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','ItemCode','Item Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','PleaseInputItemCode','Please Input Item Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','PleaseInputStoreZone','Please Input Store Zone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','PleaseSelectStoreCode','Please Select Store Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','SelectStore','Select Store');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','SelectStoreZone','Select Store Zone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','SelectZone','Select Zone');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','Stock','Stock');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stock','Zone','Zone');


delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.userinfo';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Address','Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','AllAddress','Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','AlreadySent','Sent');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Birthday','Birthday');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','BirthdayCannotBeEmpty','BirthdayCannotBeEmpty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Cancel','Cancel');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','CodeNull','Code Null');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Confirm','Confirm');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','CreateFailed','CreateFailed');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Day','Day');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','DetailDay','Please Select Date');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','DuplicateEmail','DuplicateEmail');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','DuplicateMobile','DuplicateMobile');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Email','Email');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','EmailNotValid','EmailNotValid');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','EmailNull','Email is blank');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Female','Female');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','GetCode','Get Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','GivenName','GivenName');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','GivenNameCannotBeEmpty','GivenNameCannotBeEmpty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','ID','VIP Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','InvalidRegId','InvalidRegId');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','LoginSuccess','LoginSuccess');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Male','Male');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','MdyPass','Mdy Pass');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Mobile','Mobile');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Month','Month');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Name1Null','Please Input First Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Name2Null','Please Input Last Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','NameNull','Please Input Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','NewEmail','Please Input Email Adress');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','NewMobile','Please Input Telephone No');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Password','Password');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','RegSuccessAndLogin','RegSuccessAndLogin');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Register','Register');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','RightEmail','Invalid Email Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','RightTel','Invalid Phone Number');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Secrecy','Unspecified');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Sex','Sex');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','SexCannotBeEmpty','SexCannotBeEmpty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Surname','Surname');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','SurnameCannotBeEmpty','SurnameCannotBeEmpty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','TelNotValid','TelNotValid');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','TelNull','Please input Tel');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','TelOrEmailNotValid','TelOrEmailNotValid');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','UserName','Name');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','UserNameCannotBeEmpty','UserNameCannotBeEmpty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','WriteCode','Write Code');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','Year','Year');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','female','Female');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','male','Male');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.userinfo','secrecy','Secrecy');



delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.vipdetail';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','AccountDetails','Account Details');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','AllOrders','All Orders');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','BindWechat','Link WeChat');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','BonusQuery','Bonus Points');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Cart','Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Collection','Collection');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Coupon','Coupon');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Footprint','Footprint');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Giftcert','Gift Cert');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','LastSalesDate','Last Sales Date');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','LastShop','Last Shop');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Logout','Logout');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','MyOrders','My Order');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','NoEvaluate','No Evaluate');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','NoReceiving','No Receiving');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Obligation','Obligation');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Privilege','Privilege');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','ReceiverAddress','Recipient Address');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','Set','Set');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.vipdetail','VipPrefEmpty','No Sales Record Found');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.alipay';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.alipay','AliPay','AliPay');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.alipay','Closed','Closed');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.alipay','NotPay','Payment Incompleted');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.alipay','PayCancel','Payment Canceled');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.alipay','PayCancelConfirm','Are You Sure to Cancel Payment?');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.alipay','PayDone','Payment Completed');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.alipay','TradeState','Trade Status');



delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.emptycart';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.emptycart','Empty','Empty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.emptycart','GoShopping','Go Shopping');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.modifypass';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.modifypass','NewPassNull','NewPassNull');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.modifypass','OldPass','Old Password');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.modifypass','PassNull','PassNull');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.modifypass','PassSame','PassSame');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.modifypass','RePassNull','RePassNull');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.modifypass','ReSetNewPass','Confirm New Password');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.modifypass','SetNewPass','New Password');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.modifypass','Submit','Submit');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.search';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','AddToCardSuccess','Added to Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','AddToCart','Add To Cart');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','Color','Color');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','Count','Quantity');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','NoCode','NoCode');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','NoItemFound','Item Not Found');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','NoMore','No More Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','NoMoreRecord','No More Record');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','ScanResult','Scan Result');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','SelectColorSizeFirst','Select Color Size');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.search','Size','Size');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.stockinfo';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stockinfo','Filter0','Filter 0 Qty');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stockinfo','INT','INT');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stockinfo','NoMoreRecords','No More Records');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stockinfo','NoRecord','No Record Found');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stockinfo','QOH','QOH');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.stockinfo','QohOnly','QOH Only');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'ShopHelper.wxpay';
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','Closed','Closed');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','NotPay','Payment Incompleted');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','PayCancel','Payment Canceled');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','PayCancelConfirm','Are You Sure to Cancel Payment?');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','PayDone','Payment Completed');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','PayError','Payment Error');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','Refund','Refund');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','Revoked','Revoked');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','TradeState','Trade Status');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','UserPaying','Payment In Progress');
INSERT INTO xf_langmap (XF_LANGTYPE,XF_FUNCTIONID,XF_MSGID,XF_CONTENT) VALUES ('en','ShopHelper.wxpay','WxPay','WeChat Payment');
