----------------------------------------------- zh_CN -----------------------------------------------
delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.home';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.home', 'AppTitle', '科传租户自助平台');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.home', 'CopyRight', '系统最终解释权归广州科传股份有限公司所有');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.settlememolist';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememolist', 'ContractNo', '合同号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememolist', 'SettleDocNo', '结算单号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememolist', 'AccountMonth', '账期');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememolist', 'SettleGroup', '结算组别');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememolist', 'SettleAmount', '含税金额');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememolist', 'ReceiveAmount', '');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememolist', 'NotReceiveAmount', '');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememolist', 'Details', '详情');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.settlememodetail';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'SettleMemo', '结算单');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'ContractNo', '合同编号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'SettleDocNo', '结算单号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'SettleGroup', '结算组别');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'ChargeDesc', '费用科目');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'AccountMonth', '账期');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'To', '至');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'AmtTE', '不含税金额');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'Tax', '税额');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'AmtTI', '含税金额');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'SubTotal', '小计');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'Total', '总计');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'Confirm', '确定');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'Reject', '撤回');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'ConfirmSettleMemo', '是否确认结算单？');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'RejectSettleMemo', '撤回结算单');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.settlememodetail', 'RejectReason', '请填写撤回理由');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.salesdetail';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'SalesDetail', '销售明细');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'DataErrorMsg', '起止时间不正确,请检查');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'TenderDetail', '付款汇总');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'TxDate', '交易日期');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'To', '至');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'SortOrder', '排序方式');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'DateAsc', '日期 升序');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'DateDesc', '日期 降序');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'CountAsc', '笔数 升序');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'CountDesc', '笔数 降序');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'Search', '搜索');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'Store', '店铺');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'Tender', '付款方式');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'Amount', '金额');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'Count', '笔数');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'Qty', '数量');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'SubTotal', '小计');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salesdetail', 'Total', '总计');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.salessubmit';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'SalesSubmit', '报销售');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'StoreCode', '店铺号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'TillId', '收银机号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'TxDate', '交易日期');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'RefDocNo', '参考单号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'ItemCode', '商品号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'TxQty', '交易数量');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'TxCount', '交易笔数');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'TenderDetais', '收款明细');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'TotalAmount', '总金额');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'Confrim', '确定');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'SubmitSuccess', '提交成功');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'BeforeMonthEndDate', '不能录入月结日之前的记录');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'NoTenderInput', '请至少输入一个付款金额');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'SalesInputMaxDate', '交易日期比销售录入日期早,如需更改,请在后台系统设定中维护');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'LimitDateConfig', '您的销售日期限定值录入有误,如需更改,请在后台系统设定中维护');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'LimitDateRange', '交易日期必须在这个范围内:');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'RecordDuplicate', '已存在相同记录(店铺,收银机号,交易日期,参考单号,商品号)');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'LimitTime', '不能录入前一天的销售数据');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.salessubmit', 'LimitCount', '当天已录入过销售数据，每天只能录入一次销售数据');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.notice';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.notice', 'MyNotice', '我的消息');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.notice', 'MallNotice', '商场公告');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.notice', 'EndDate', '结束日期');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.suggestlist';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'SuggestList', '投诉列表');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'SuggestNo', '投诉单号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'SuggestContent', '投诉内容');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'SuggestBy', '投诉人');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'SuggestDate', '投诉日期');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'Status', '状态');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'DisposeContent', '处理方案');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'DisposeBy', '处理人');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'DisposeDate', '处理日期');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'Suggest', '投诉');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggestlist', 'Dispose', '处理');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.suggest';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'Suggest', '投诉');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'AutoGen', '自动生成');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'SuggestNo', '投诉单号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'Content', '请在此输入内容,最多可上传5张图片');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'Confirm', '提交');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'Delete', '删除');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'ContentInvalid', '请输入内容');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'DisposeBy', '处理人');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'DisposeDate', '处理日期');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'SuggestNoDuplicate', '投诉单号已存在');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'UpdateSuccess', '更新成功');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'DeleteSuccess', '删除成功');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.suggest', 'UploadTooMuch', '最多上传5张图片');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'mobiletenant/set';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'Set', '系统设定');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'ModifyPwd', '修改密码');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'Style', '系统风格');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'Language', '系统语言');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'Logout', '注销登录');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'Default', '默认');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'NavyBlue', '海军蓝');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'Green', '典雅绿');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/set', 'Black', '幻影黑');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'mobiletenant/login';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/login', 'Login', '账户登录');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/login', 'LoginMsg', '欢迎使用科传租户自助平台');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/login', 'LoginNow', '立即登录');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/login', 'LoginStaffCode', '请输入员工号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/login', 'LoginPassword', '请输入密码');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/login', 'LoginFail', '登录失败');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'mobiletenant/modifypwd';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/modifypwd', 'ModifyPwd', '修改密码');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/modifypwd', 'OldPwd', '请输入旧密码');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/modifypwd', 'NewPwd', '请输入新密码');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/modifypwd', 'ConfirmNewPwd', '请再次输入新密码');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/modifypwd', 'Confirm', '确定');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/modifypwd', 'EqualsToOldPwd', '新密码与旧密码相同');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/modifypwd', 'ConfirmNewPwdInvalid', '两次输入的新密码不一致');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'mobiletenant/handbook';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'mobiletenant/handbook', 'HandBook', '租户手册');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.repairlist';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repairlist', 'RepairList', '报修列表');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repairlist', 'ToRepair', '我要报修');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repairlist', 'DocNo', '单号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repairlist', 'LocCode', '保修地点');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repairlist', 'ReqRemark', '申请事项');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repairlist', 'RequestBy', '申请人');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repairlist', 'RequestDate', '申请日期');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repairlist', 'Status', '状态');

delete from xf_langmap where xf_langtype = 'zh_CN' and xf_functionid = 'MobileTenant.repair';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'ToRepair', '我要报修');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'DocNo', '单号');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'Status', '状态');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'LocCode', '报修地点');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'Floor', '楼层');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'Telephone', '电话');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'ReqRemark', '申请事项');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'CaseDescription', '情况描述');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'LocCodeRequire', '请输入报修地点');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'Confirm', '提交');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'Delete', '删除');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'UpdateSuccess', '更新成功');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'DeleteSuccess', '删除成功');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('zh_CN', 'MobileTenant.repair', 'UploadTooMuch', '最多上传5张图片');
commit;