----------------------------------------------- en -----------------------------------------------
delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.home';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.home', 'AppTitle', 'Tech-Trans Tenant Self-Help Platform');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.home', 'CopyRight', 'Copyright © Tech-Trans. All Rights Reserved.');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.settlememolist';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememolist', 'ContractNo', 'Contract No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememolist', 'SettleDocNo', 'Settle No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememolist', 'AccountMonth', 'Date Range');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememolist', 'SettleGroup', 'Group');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememolist', 'SettleAmount', 'Tax Amount');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememolist', 'ReceiveAmount', 'Receive amount');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememolist', 'NotReceiveAmount', 'Not receive amount');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememolist', 'Details', 'Details');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.settlememodetail';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'SettleMemo', 'Settle Memo');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'ContractNo', 'Contract No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'SettleDocNo', 'Settle No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'SettleGroup', 'Group');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'ChargeDesc', 'Charge desciption');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'AccountMonth', 'Date Range');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'To', 'to');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'AmtTE', 'AmtTE');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'Tax', 'Tax');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'AmtTI', 'AmtTI');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'SubTotal', 'Sub total');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'Total', 'Total');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'Confirm', 'Confirm');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'Reject', 'Reject');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'ConfirmSettleMemo', 'Is the statement of account confirmed？');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'RejectSettleMemo', 'Withdrawal of a bill of settlement');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.settlememodetail', 'RejectReason', 'Please input the reason for the withdrawal');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.salesdetail';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'SalesDetail', 'Sales Detail');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'DataErrorMsg', 'Invalid TxDate, Please Check');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'TenderDetail', 'Tender Detail');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'TxDate', 'TxDate');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'To', 'To');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'SortOrder', 'Sort By');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'DateAsc', 'Date Ascending');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'DateDesc', 'Date Descending');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'CountAsc', 'Tx Count Ascending');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'CountDesc', 'Tx Count Descending');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'Search', 'Search');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'Store', 'Store');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'Tender', 'Tender');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'Amount', 'Amount');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'Count', 'Count');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'Qty', 'Qty');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'SubTotal', 'Sub Total');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salesdetail', 'Total', 'Total');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.salessubmit';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'SalesSubmit', 'Sales Submit');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'StoreCode', 'Store Code');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'TillId', 'Till Id');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'TxDate', 'Tx Date');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'RefDocNo', 'Ref Doc No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'ItemCode', 'Item Code');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'TxQty', 'Tx Qty');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'TxCount', 'Tx Count');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'TenderDetais', 'Tender Details');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'TotalAmount', 'Total Amount');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'Confrim', 'Confirm');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'SubmitSuccess', 'Submit Success');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'BeforeMonthEndDate', 'Tx Date Can not before Month End Date');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'NoTenderInput', 'Plese enter at least one tender');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'SalesInputMaxDate', 'Tx Date is earlier than Sales Input Date, You can config this at esPOS system');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'LimitDateConfig', 'Limit Date Config Error, You can config this at esPOS system');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'LimitDateRange', 'Tx Date range must between:');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'RecordDuplicate', 'Record duplicate(Store,Till Id, Tx Date, Ref Doc No, Item Code)');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'LimitTime', 'You can not enter the sales data of the previous day');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.salessubmit', 'LimitCount', 'Sales data have been entered that day, only one sales data can be entered once a day');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.notice';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.notice', 'MyNotice', 'My Notice');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.notice', 'MallNotice', 'Mall Notice');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.notice', 'EndDate', 'End Date');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.suggestlist';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'SuggestList', 'Suggest List');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'SuggestNo', 'Doc No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'SuggestContent', 'Suggest Content');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'SuggestBy', 'Suggest By');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'SuggestDate', 'Suggest Date');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'Status', 'Status');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'DisposeContent', 'Dispose Content');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'DisposeBy', 'Dispose By');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'DisposeDate', 'Dispose Date');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'Suggest', 'Suggest');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggestlist', 'Dispose', 'Dispose');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.suggest';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'Suggest', 'Suggest');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'AutoGen', 'Auto Gen');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'SuggestNo', 'Doc No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'Content', 'Please input content here, you can upload up to 5 pictures');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'Confirm', 'Confirm');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'Delete', 'Delete');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'ContentInvalid', 'Please input content');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'DisposeBy', 'Dispose By');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'DisposeDate', 'Dispose Date');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'SuggestNoDuplicate', 'Doc No Duplicate');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'UpdateSuccess', 'Update Success');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'DeleteSuccess', 'Delete Success');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.suggest', 'UploadTooMuch', 'You can only upload up to 5 pictures');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'mobiletenant/set';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'Set', 'Setting');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'ModifyPwd', 'Modify Password');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'Style', 'Style');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'Language', 'Language');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'Logout', 'Logout');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'Default', 'Default');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'NavyBlue', 'Navy Blue');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'Green', 'Green');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/set', 'Black', 'Black');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'mobiletenant/login';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/login', 'Login', 'Login');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/login', 'LoginMsg', 'Welcome to Tech-Trans Tenant Self-Help Platform');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/login', 'LoginNow', 'Login');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/login', 'LoginStaffCode', 'Please input the staff code');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/login', 'LoginPassword', 'Please input the password');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/login', 'LoginFail', 'Login fail');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'mobiletenant/modifypwd';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/modifypwd', 'ModifyPwd', 'Modify Password');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/modifypwd', 'OldPwd', 'Please input old password');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/modifypwd', 'NewPwd', 'Please input new password');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/modifypwd', 'ConfirmNewPwd', 'Please input new password again');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/modifypwd', 'Confirm', 'Confirm');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/modifypwd', 'EqualsToOldPwd', 'New password equals to Old password');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/modifypwd', 'ConfirmNewPwdInvalid', 'New passwords are different');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'mobiletenant/handbook';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'mobiletenant/handbook', 'HandBook', 'Hand Book');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.repairlist';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repairlist', 'RepairList', 'Repair List');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repairlist', 'ToRepair', 'To Repair');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repairlist', 'DocNo', 'Doc No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repairlist', 'LocCode', 'Location of repair');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repairlist', 'ReqRemark', 'Request Remark');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repairlist', 'RequestBy', 'Request By');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repairlist', 'RequestDate', 'Request Date');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repairlist', 'Status', 'Status');

delete from xf_langmap where xf_langtype = 'en' and xf_functionid = 'MobileTenant.repair';
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'ToRepair', 'To Repair');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'DocNo', 'Doc No');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'Status', 'Status');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'LocCode', 'Location of repair');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'Floor', 'Floor');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'Telephone', 'Telephone');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'ReqRemark', 'Request Remark');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'CaseDescription', 'Case description');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'LocCodeRequire', 'Please enter the location of the repair');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'Confirm', 'Confirm');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'Delete', 'Delete');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'UpdateSuccess', 'Update Success');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'DeleteSuccess', 'Delete Success');
insert into xf_langmap(xf_langtype, xf_functionid, xf_msgid, xf_content) values ('en', 'MobileTenant.repair', 'UploadTooMuch', 'You can only upload up to 5 pictures');
